title: akromio
description: Suite de automatización para equipos de IT
baseurl: /
google_analytics: G-Z2FF4NRNY9

brand:
  name: Akromio
  author: Sia Codelabs
ws:
  year: 2022-2023

plugins:
  - jekyll-remote-theme
  - jekyll-sitemap

remote_theme: jekyll/minima
minima:
  skin: auto
  social_links:
    - platform: github
      user_url: https://github.com/akromio
    - platform: twitter
      user_url: https://twitter.com/siacodelabs

collections:
  sponsorship:
    title: Patrocinio
    output: true
    permalink: /:collection/:path
    order:
      - patrocinio.md
      - roadmap.md
  doc:
    title: Documentación
    output: true
    permalink: /:collection/:path
    order:
      - instalación.md
      - datos.md
      - catálogos.md
      - registros.md
      - extensiones.md
      - disparadores.md
      - ejecución-distribuida.md
      - plugins.md

defaults:
  - scope:
      path: ""
      type: doc
    values:
      layout: page
  - scope:
      path: ""
      type: sponsorship
    values:
      layout: page
