title: Akromio
locale: es_ES
tagline: Suite de automatización para equipos de IT
description: |
  Akromio es una suite de automatización de tareas realizadas comúnmente por
  desarrolladores de software, administradores, pentesters y otros roles de IT.
baseurl: /
google_analytics: G-Z2FF4NRNY9

author:
  name: Sia Codelabs
  twitter: siacodelabs

twitter:
  card: summary
  username: siacodelabs

ws:
  year: 2022-2023

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme

remote_theme: jekyll/minima
minima:
  skin: auto
  social_links:
    - platform: github
      user_url: https://github.com/akromio
    - platform: twitter
      user_url: https://twitter.com/siacodelabs

collections:
  sponsorship:
    title: Patrocinio
    output: true
    permalink: /:collection/:path
    order:
      - patrocinio.md
      - roadmap.md
  doc:
    title: Documentación
    output: true
    permalink: /:collection/:path
    order:
      - instalación.md
      - datos.md
      - catálogos.md
      - registros.md
      - extensiones.md
      - disparadores.md
      - ejecución-distribuida.md
      - plugins.md

defaults:
  - scope:
      path: ""
      type: doc
    values:
      layout: page
  - scope:
      path: ""
      type: sponsorship
    values:
      layout: page
