title: akromio
description: Documentación
url: https://akromio.com
baseurl: /

brand:
  name: Akromio
  author: Sia Codelabs
ws:
  year: 2022-2023

plugins:
  - jekyll-sitemap

remote_theme: jekyll/minima
minima:
  skin: auto
  social_links:
    - platform: github
      user_url: https://github.com/akromio
    - platform: twitter
      user_url: https://twitter.com/siacodelabs

google_analytics: G-Z2FF4NRNY9

webrick:
  headers:
    Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
    X-XSS-Protection: 1; mode=block
