title: akromio
description: Documentación
url: https://akromio.com
baseurl: /

brand:
  name: Akromio
  author: Sia Codelabs
ws:
  year: 2022

remote_theme: jekyll/minima
minima:
  skin: auto
  social_links:
    - platform: github
      user_url: https://github.com/akromio
    - platform: twitter
      user_url: https://github.com/siacodelabs

google_analytics: G-Z2FF4NRNY9
